navbar:
  background: light

  left:
    - text: Home
      href: index.qmd

    - text: About
      menu:
        - text: News
          href: posts.qmd#category=news
        - text: Events
          href: posts.qmd#category=event
        - text: Contact
          href: contact.qmd

    - text: Research
      menu:
        - text: List of Publication
          href: publications.qmd
        - text: Selected Papers
          href: posts.qmd#category=paper
        - text: Grants
          href: projects.qmd                                

    - text: Teaching
      href: teaching.qmd

    - text: Outreach
      menu:
        - text: Presentations
          href: posts.qmd#category=presentation

    - text: Group
      href: people.qmd
